  
dist: trusty
language: java
jdk:
 - oraclejdk13

addons:
 sonarcloud:
  organization: "fra199889"
  token:
   secure: "be6103bcd9224b726e7e2d3412e686ea48805e41"

script: 

- ant build
- sonar-scanner



















